### ISSUE TITLE
SessionContext is missing timeout for UserPerson

### ISSUE THREAD

**Issue by OGKevin** [bunq/sdk_php#10]
## Steps to reproduce:
1. Make a a call as user person to any endpoint

## What happens:
1. You will get  `Call to a member function getSessionTimeout() on null`.

## What should happen:
1. You don't get the mentioned error.

## Extra info:
- Tested on v 0.9.0
- https://github.com/bunq/sdk_php/issues/6#issuecomment-319994738

## Traceback

```traceback
Call to a member function getSessionTimeout() on null
bunq/sdk_php/lib/Context/SessionContext.php:60
bunq/sdk_php/lib/Context/SessionContext.php:48
bunq/sdk_php/lib/Context/ApiContext.php:149
bunq/sdk_php/lib/Context/ApiContext.php:106
 bunq/sdk_php/lib/Context/ApiContext.php:93
 bunq/sdk_php/test/ApiContextHandler.php:36
 bunq/sdk_php/test/Model/Generated/MonetaryAccountBankTest.php:69
```

**Comment by LauLaman** [comment]
Workaround:
replace [this line](https://github.com/bunq/sdk_php/blob/master/lib/Context/SessionContext.php#L60) with:
```
$expiryTime = microtime(true) + 1500;
```

**Comment by basst85** [comment]
Or replace with `$expiryTime = microtime(true) + $sessionServer->getUserPerson()->getSessionTimeout();` as workaround. 

I think there has to be a check what is used, UserCompany, UserPerson or UserLight

**Comment by OGKevin** [comment]
@basst85 Yep, that is indeed the correct workaround in case your using an UserPerson. We indeed forgot to put the check in the PHP SDK. We are looking into it 👍

**Comment by dnl-blkv** [comment]
This has been fixed in the latest version.
