### ISSUE TITLE
Document conditions for Payment.description

### ISSUE THREAD

**Issue by holtkamp** [bunq/sdk_php#108]
Next the the amount of allowed characters, are there any conditions regarding special characters when POSTing a Payment?

Observations

- the documentation does not mention them: https://doc.bunq.com/api/1/call/payment/method/post
- when using the Bunq App (Android) a Payment can be made between Bunq accounts with a description that involves a pipe `|` character, for example: `HELLO | good-bye`
- when using the API a `400 Bad Request` response is returned while using the same description

It might be an idea to:

- have behaviour that is equal for all ways to create a Payment (App + API)
- improve the returned error message
- document the requirements, is a regular expression involved? => name it in the documentation 

_PS: I know this library covers the PHP SDK and not the API documentation, but a central place for reporting and tracking API related issues is (still) missing AFAIK. I do not consider the Bunq Together forum a viable / mature alternative for an issue tracker of an API of a bank, also see https://together.bunq.com/topic/feedback-for-updating-api-documentation and annoyances like https://together.bunq.com/topic/api-method-for-retrieving-transactions#comment-2201

I suggest you guys put the API documentation in GitHub so the community can easily provide feedback using PRs, a common practice of tech-companies nowadays_

**Comment by OGKevin** [comment]
@holtkamp I suggets you to post this on together as that is our main platform for communication for now. None of the support staff looks a these issues, so for everything not SDK related please use together. 

If it turns out that the SDK is doing some magic when sending the request with the `|` then a GitHub issue is indeed needed rather then a together post but this is not the case as I understand from your issue ? It looks like the public  API does not like the `|` while the mobile API does ? Then indeed please post this on together so that it gets picked up through the proper channels. 

Closing this issue as its not SDK related, feel free to comment still.

**Comment by holtkamp** [comment]
@OGKevin ok, followed your suggestion, see https://together.bunq.com/topic/api-documentation-feedback

But please, also have a look at / actually use the Together software, it is a 👹 , difficult to search, paginate, follow discussions, etc.

**Comment by holtkamp** [comment]
2-month bump on this? As suggested I posted to [Bunq Together](https://together.bunq.com/topic/api-documentation-feedback#comment-26521), no reaction there. Is Together actively monitored?

**Comment by holtkamp** [comment]
Almost a year later it appears the link of the documentation https://doc.bunq.com/api/1/call/payment/method/post has changed to : https://doc.bunq.com/#/payment/Create_Payment_for_User_MonetaryAccount, which currently states about the `description`:

> The description for the Payment. Maximum 140 characters for Payments to external IBANs, 9000 characters for Payments to only other bunq MonetaryAccounts.

Does this mean the "pipe" character `|` as in `HELLO | good-bye` is now allowed as part of the description?

Still no feedback in https://together.bunq.com/d/714-api-documentation-feedback

**Comment by basst85** [comment]
Hello @holtkamp 

The pipe (vertical line) character in the description is only allowed for payments to other bunq customers.

Special characters (and emojis) are not allowed for SEPA Credit Transfers (PAIN.001). 
In ISO20022 Payment Initiation messages the UTF8 character set must be used. The Latin character set, which is commonly used for international communication, must be used.

**Comment by holtkamp** [comment]
@basst85 

Thanks, I think this should be part of the documentation, for example, [this document](https://www.rabobank.com/en/images/format-description-sepa-credit-transfer-pain-001-001-03-okt.pdf) mentions it explicitly:

> 1.2.3 Character set
In ISO20022 Payment Initiation messages the UTF8 character set must be used. The Latin character set, which is commonly
used for international communication, must be used. Rabobank accepts the following characters:1
• a b c d e f g h i j k l m n o p q r s t u v w x y z
• A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
• 0 1 2 3 4 5 6 7 8 9
• / *- ? : ( ) . , ‘ + space

just my two cents 😄

**Comment by holtkamp** [comment]
@basst85 so the documentation has been updated:

- https://doc.bunq.com/api/1/call/payment/method/post 

leads to the general documentation (no forwarding to appropriate section?) and should now probably be

- https://doc.bunq.com/#/payment/Create_Payment_for_User_MonetaryAccount
_Technical_ conditions other than a limit for the Payment.description property seem not documented in detail...
<img width="945" alt="Screenshot 2019-10-04 at 12 54 19" src="https://user-images.githubusercontent.com/776405/66202491-2cacea00-e6a6-11e9-963f-9c4d16eada8c.png">
