### ISSUE TITLE
Can not construct a BunqMeTabEntry for use with BunqMeTab::create()

### ISSUE THREAD

**Issue by mbernson** [bunq/sdk_php#118]
## Steps to reproduce:
1. In order to send a shared request (bunq.me tab), I need to pass a BunqMeTabEntry object. However, I can't construct such an object properly.

## What should happen:
1. I can construct the object however I want, or just pass a requestMap (array).

## What happens:
1. I construct the object and get superfluous field errors.

## SDK version and environment
- Tested on [0.13.1](https://github.com/bunq/sdk_php/releases/tag/0.13.1)
- [x] Sandbox
- [x] Production

**Comment by OGKevin** [comment]
Re opening as Objects should include this as well.
