### ISSUE TITLE
Draft Payments is missing

### ISSUE THREAD

**Issue by georgeboot** [bunq/sdk_php#13]
Though the SDK I can create regular payments, but there is no way to create a `DraftPayment` - it seems the model is missing.

Is this correct, or is there a (hidden) option on `Payment` to make it a draft instead of a regular one?

**Comment by OGKevin** [comment]
Hey @georgeboot,

Thanks for reporting this 👍, we're looking into it.

**Comment by OGKevin** [comment]
Closing in favor of #15 

@georgeboot FYI

**Comment by georgeboot** [comment]
How do you mean this exactly? #15 does not implement this feature, does it?

**Comment by dnl-blkv** [comment]
@georgeboot the PR for it did add the model. It was a large one %). We'll try splitting them up for clarity further on.

**Comment by basst85** [comment]
@georgeboot https://github.com/bunq/sdk_php/blob/develop/src/Model/Generated/DraftPayment.php

**Comment by georgeboot** [comment]
Ah now it makes sense: the #15 links issue 15, not PR. Hence the misunderstanding 👍🏻
