### ISSUE TITLE
[epic] Revamp readme 

### ISSUE THREAD

**Issue by OGKevin** [bunq/sdk_php#139]
Whit the release of tinker, we will now use that as example. So example references to the example folder should be pointed to tinker code.

**Comment by OGKevin** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/git-pull-request.svg) [Replace examples with tinker bunq/sdk_pyhton#68 #84](https://github.com/bunq/sdk_python/issues/84) | 0.13.5 | OGKevin | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by Wouter0100** [comment]
Listing monetary accounts example does not seem to work. Corrected one:

```
$monetaryAccountList = MonetaryAccount::listing();

foreach ($monetaryAccountList->getValue() as $monetaryAccount) {
    var_dump($monetaryAccount->getReferencedObject()->getDescription() . PHP_EOL);
}
``

**Comment by OGKevin** [comment]
@Wouter0100 😁 nice stop, feel free to create a PR to fix this :). Do you mind checking the readme's of the other 2 SDK's and create a PR ? They are referenced in the comment above.

**Comment by Wouter0100** [comment]
Sure! @OGKevin I'll get back to you asap when I have a complete overview and implemented the features I need :)
