### ISSUE TITLE
Error retrieving pinned certificates

### ISSUE THREAD

**Issue by BabyDino** [bunq/sdk_php#14]
```
$apiContext = ApiContext::restore(BUNQ_CONFIG);
$certificateList = CertificatePinned::listing($apiContext, BUNQ_USER_ID);
```
Provides an error: 

`Argument 1 passed to bunq\Model\BunqModel::createListFromResponseArray() must be of the type array, string given, called in vendor\bunq\sdk_php\lib\Model\BunqModel.php on line 160`

**Comment by OGKevin** [comment]
Hey @BabyDino,

Thanks for reporting this. Lets see if I can reproduce and see whats going on here 👍

**Comment by BabyDino** [comment]
@OGKevin FYI, I have already one certificate pinned. But that shouldn't matter :)

**Comment by OGKevin** [comment]
Managed to reproduce, looking for a fix. Thx for reporting @BabyDino 🤗

**Comment by OGKevin** [comment]
We've managed to figure out what is causing it, unfortunately there is no quick fix for this and it will be fixed in a future patch 👍

**Comment by OGKevin** [comment]
Closing in favour of #43
