### ISSUE TITLE
Move to new sandbox 

### ISSUE THREAD

**Issue by OGKevin** [bunq/sdk_php#149]
The new sandbox url will be `https://public-api.sandbox.bunq.com/v1/`.

This new environment will not support pub key pinning due to a bug in curl, see: https://curl.haxx.se/docs/todo.html#Support_intermediate_root_pinn. Therefore, public key pinning will be disabled in the SDK's for sandbox.  

Together post: PENDING

**Comment by OGKevin** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Move to new sandbox env.  #98](https://github.com/bunq/sdk_python/issues/98) | 0.13.5 | OGKevin | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by Dew0Tgx** [comment]
[https://opac.tib.eu/DB=1/LNG=EN/LRSET=1/SET=1/SID=833254a4-25/TTL=1/RESULTS_SAVEINFO_LONG?FRST=1&LAST=1&HITS=1&PPN=496421530https://opac.tib.eu/DB=1/LNG=EN/LRSET=1/SET=1/SID=833254a4-25/TTL=1/RESULTS_SAVEINFO_LONG?FRST=1&LAST=1&HITS=1&PPN=496421530]()

**Comment by Dew0Tgx** [comment]
> [https://opac.tib.eu/DB=1/LNG=EN/LRSET=1/SET=1/SID=833254a4-25/TTL=1/RESULTS_SAVEINFO_LONG?FRST=1&LAST=1&HITS=1&PPN=496421530https://opac.tib.eu/DB=1/LNG=EN/LRSET=1/SET=1/SID=833254a4-25/TTL=1/RESULTS_SAVEINFO_LONG?FRST=1&LAST=1&HITS=1&PPN=496421530]()

**Comment by Dew0Tgx** [comment]
[CODESANDBOX ]()

**Comment by hittojeah90** [comment]
https://public-api.sandbox.bunq.com/v1/
