### ISSUE TITLE
Missing MonetaryAccountSavings

### ISSUE THREAD

**Issue by OGKevin** [bunq/sdk_php#165]
## Steps to reproduce:
1. Have a `MonetaryAccountSavings`
2. Make a call to `monetary-account` endpoint.
3. make a function call to https://github.com/bunq/sdk_php/blob/1ca394e69959a25faf95e56d499daa6ed567da4f/src/Model/Generated/Endpoint/MonetaryAccount.php#L165-L179

## What should happen:
1. You get this new type

## What happens:
1. Explosions.

## Traceback
- see https://github.com/firefly-iii/firefly-iii/issues/1857

## SDK version and environment
- Tested on [1.2.0](https://github.com/bunq/sdk_php/releases/tag/1.2.0)
- [ ] Sandbox
- [x] Production

**Comment by kojoru** [comment]
I'm glad to announce that this issue is finally fixed as of version 1.2.2.

**Comment by OGKevin** [comment]
Closing this one as it has been fixed in https://github.com/bunq/sdk_php/releases/tag/1.2.2
