### ISSUE TITLE
Incorrect name space for BunqException

### ISSUE THREAD

**Issue by OGKevin** [bunq/sdk_php#166]
## Steps to reproduce:
1. Trigger an BunqException from generated code

## What should happen:
1. The exception gets thrown 

## What happens:
1. Because the generated code is using an incorrect namespace, a fatal happends.

## Traceback
- see https://github.com/firefly-iii/firefly-iii/issues/1857

## SDK version and environment
- Tested on [1.2.0](https://github.com/bunq/sdk_php/releases/tag/1.2.0)
- [ ] Sandbox
- [x] Production

## Extra info:
<https://github.com/bunq/sdk_php/blob/982bd08d43293c2766c7fcc094cd55b4e6b06687/src/Exception/BunqException.php#L2>

https://github.com/bunq/sdk_php/blob/982bd08d43293c2766c7fcc094cd55b4e6b06687/src/Model/Generated/Endpoint/MonetaryAccount.php#L4

**Comment by filoor** [comment]
Any idea when this will be fixed?

**Comment by OGKevin** [comment]
> Any idea when this will be fixed?

🤷‍♂️ unfortunately, I can't fix this as I no longer have access to the generator. This is a bug in the generator and therefore needs bunq's internal people to fix it.

e.g: @kojoru @JordyHeemskerk

**Comment by filoor** [comment]
Thanks @OGKevin thanks,
Hope that @kojoru @JordyHeemskerk will soon have time for it can not import my data now in firefly iii :(

**Comment by OGKevin** [comment]
Can this plz be fixed -.-.  its a simple generator code template typo.

**Comment by angelomelonas** [comment]
@OGKevin I have fixed this on the generator so this will be fixed in the next planned release (1.14.1).

**Comment by OGKevin** [comment]
I longer use bunq 🤷.
