### ISSUE TITLE
Not receive schedule payment status (sdk_php)

### ISSUE THREAD

**Issue by GytisTo** [bunq/sdk_php#170]
## Steps to reproduce:
Create schedule payment and printed info about that payment

print_r($payment->getPayment()->getAmount()->getValue());
echo "</br>";
print_r($payment->getSchedule()->getTimeStart());
echo "</br>";
print_r($payment->getSchedule()->getStatus()); //only this one return empty
echo "</br>";
print_r($payment->getPayment()->getCounterpartyAlias()->getDisplayName());
echo "</br>";
print_r($payment->getPayment()->getCounterpartyAlias()->getIban());
echo "</br>";
## What should happen:
get all info about that payment

## What happens:
didnt get payment status in both enviroments

## Traceback
[//]: # (If there is a traceback please share it in a quote! You can do this by pasting the traceback text, highlighting it and pressing the quote button.)

## SDK version and environment
- [ ] Sandbox
- [ ] Production

## Extra info:
Im using sdk_php, also all other (at least i am using) i recieve , just can't get schedule payment status

**Comment by basst85** [comment]
Extra info:

It looks like the SDK is looking in the wrong object. 
The status is inside the "ScheduledPayment" object, not in "Schedule" or "Payment".

**Comment by OGKevin** [comment]
I don't quite understand. @GytisTo could you please update the issue body to make it clear what is failing and properly format the issue. Plz use [markdown formatting](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet). 

@basst85 how did you come to this conclusion? Did you manage to get a raw response ?

**Comment by GytisTo** [comment]
> I don't quite understand. @GytisTo could you please update the issue body to make it clear what is failing and properly format the issue. Plz use [markdown formatting](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).
> 
> @basst85 how did you come to this conclusion? Did you manage to get a raw response ?

**Comment by basst85** [comment]
> @basst85 how did you come to this conclusion? Did you manage to get a raw response ?

Yes, i managed to get the raw response. Check this: https://pastebin.com/Lj4bEvmw

**Comment by OGKevin** [comment]
yup, @basst85 you're correct 👍 

@kojoru view definition mistake... this needs regeneration to fix it.

**Comment by GytisTo** [comment]
So i need take more info or its clear now what the problem is? :)

**Comment by OGKevin** [comment]
yea its clear @GytisTo

**Comment by GytisTo** [comment]
Cool :) inform me if you fix the problem or find other way to reach status :)

**Comment by GytisTo** [comment]
well if there is way to get status from sdk_php it would be nice :)

**Comment by OGKevin** [comment]
You can add

```
    /**
     * The schedule status, options: ACTIVE, FINISHED, CANCELLED.
     *
     * @var string
     */
    protected $status;

```

in https://github.com/bunq/sdk_php/blob/e9511e1c158a2c8d768d167bc05a66d7d88ea5d5/src/Model/Generated/Endpoint/SchedulePayment.php

and ofc its getters to get the status.

**Comment by GytisTo** [comment]
will try thanks :)

**Comment by GytisTo** [comment]
added your code and this:
 `
public function getStatus()
    {
        return $this->status;
    }
`
looks like its working, thanks for help :)

**Comment by GytisTo** [comment]
I find interesting thing working on SANDBOX : if you use ` SchedulePayment::get` you will get right one status but if you use `SchedulePayment::listing` to see status you will get all payments "ACTIVE" although there are payments which are "FINISHED" or "CANCELLED" .  Also there is way to get specific days payments( for example these days) cause i know only there is 
`$pagination = new Pagination();
	$pagination->setCount(2);
	$list = SchedulePayment::listing($monetaryAccount->getId(),$pagination->getUrlParamsCountOnly())->getValue()`
where you number of payments you wont to get

**Comment by GytisTo** [comment]
is this also kinda bug @OGKevin @basst85 ?
