### ISSUE TITLE
Can't use public functions in endpoints

### ISSUE THREAD

**Issue by nouce** [bunq/sdk_php#172]
## Steps to reproduce:
1. If i want to display the user persons public nick name i need to do it like this:
```
use bunq\Model\Generated\Endpoint\UserPerson;
use bunq\Model\Generated\Endpoint\Payment;

$apiContext = ApiContext::restore(storage_path('bunq/bunq.conf'));
$bunqContext = BunqContext::loadApiContext($apiContext);

$userPerson = UserPerson::get();
dd($userPerson->getPublicNickName());
```

According to the bunq sdk_php documantation.

## What should happen:
1. It should output the public nick name

## What happens:
1. I get this error 
`Call to undefined method bunq\Model\Generated\Endpoint\BunqResponseUserPerson::getPublicNickName()`

## SDK version and environment
- Tested on [0.12.4](https://github.com/bunq/sdk_php/releases/tag/0.12.4)
- [x] Sandbox
- [ ] Production

## Extra info:
[//]: # (Please provide any other relevant information here)

**Comment by basst85** [comment]
Hello @nouce , i think you forget to use "getValue()" first 🙂

This works:

```php
$userPerson = UserPerson::get();
echo $userPerson->getValue()->getPublicNickName();
```

**Comment by nouce** [comment]
Jup, that works! Thanks for the help men 👍🏻
