### ISSUE TITLE
TransferwiseTransfer property on EventObject is not populated

### ISSUE THREAD

**Issue by dorxy** [bunq/sdk_php#176]
## Steps to reproduce:
1. Fetch an event related to a Transferwise transfer 

## What should happen:
1. The transferwiseTransfer property of the EventObject should contain a `TransferwiseTransfer`

## What happens:
1. It is not populated, as the API returns a property called `TransferwisePayment`

Note: I'm using the sandbox environment to test this

**Comment by basst85** [comment]
I can also simulate this in sandbox and production.  
The object type in the Event response is indeed `TransferwisePayment` and not `TransferwiseTransfer`

**Comment by lexym** [comment]
Fixed!
