### ISSUE TITLE
Fout! Use of undefined constant CURLOPT_PINNEDPUBLICKEY - assumed 'CURLOPT_PINNEDPUBLICKEY' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by udsolutions** [bunq/sdk_php#178]
## Steps to reproduce:
1. Assign Bunq API key to a third party software

## What should happen:
1. Connection establishment instead of error

## What happens:
1. Error occurs when trying to establish a connection with API:
Fout! Use of undefined constant CURLOPT_PINNEDPUBLICKEY - assumed 'CURLOPT_PINNEDPUBLICKEY' (this will throw an Error in a future version of PHP)

## Traceback
[//]: # (If there is a traceback please share it in a quote! You can do this by pasting the traceback text, highlighting it and pressing the quote button.)

## SDK version and environment
- Tested on [0.12.4](https://github.com/bunq/sdk_php/releases/tag/0.12.4)
- [ ] Sandbox
- [ x ] Production

## Response id
[//]: # (If this error has something to do with a request that fails, please provide the response id of the request.)
- Response id:

## Extra info:
[//]: # (Please provide any other relevant information here)
Using Firefly iii
PHP Version 7.3.8

**Comment by PGPNINJA** [comment]
Workaround is uncommenting line 315 in the conf
