### ISSUE TITLE
Balance is null

### ISSUE THREAD

**Issue by Tantuss** [bunq/sdk_php#194]
## Steps to reproduce:
Small piece of PHP code:
$monetaryAccounts = MonetaryAccount::listing()->getValue();
foreach ($monetaryAccounts as $monetaryAccount) {
    $account = $monetaryAccount->getMonetaryAccountBank();
    $balance = $account->getBalance()->getValue();
}

This '$account->getBalance()' is already returning NULL, so the getValue() is generating an error.

## What should happen:
1. Get a balance back.

## What happens:
1. Balance is NULL, what isn't correct. There is for sure money on the accounts.

## SDK version and environment
- Tested on [0.13.1](https://github.com/bunq/sdk_php/releases/tag/0.13.1)
- PHP 7.2.27-5+0~20200202.35+debian9~1 (cli)
- [ ] Sandbox
- [ X ] Production

**Comment by basst85** [comment]
> ## Steps to reproduce:
> Small piece of PHP code:
> $monetaryAccounts = MonetaryAccount::listing()->getValue();
> foreach ($monetaryAccounts as $monetaryAccount) {
> $account = $monetaryAccount->getMonetaryAccountBank();
> $balance = $account->getBalance()->getValue();
> }
> 
> This '$account->getBalance()' is already returning NULL, so the getValue() is generating an error.
> 

Hello!

This code works on my machine, it returns the balances of all active monetary accounts:

```PHP
$monetaryAccountList = MonetaryAccountBank::listing([])->getValue();

foreach ($monetaryAccountList as $monetaryAccount) {
	if ($monetaryAccount->getStatus() === 'ACTIVE') {
		echo $monetaryAccount->getBalance()->getValue() . '<br/>';
	}
}
```

**Comment by Tantuss** [comment]
Is it possible to do some setting in the app to hide your balance in the API?

**Comment by basst85** [comment]
> Is it possible to do some setting in the app to hide your balance in the API?

Nope, your account balances are always visible via the API

**Comment by Tantuss** [comment]
I tried with another Bunq account, then it works fine.
I attached the debugger and then I really see that the balance value is null, so it looks like it's some issue in the Bunq API and not in this library.

**Comment by Tantuss** [comment]
I think it's some security issue, I will send a detailed report how to reproduce directly to the support of Bunq. So their tech support can look into it.
