### ISSUE TITLE
guzzle: Call to undefined function GuzzleHttp\Psr7\parse_query()

### ISSUE THREAD

**Issue by timvisee** [bunq/sdk_php#217]
## Steps to reproduce:
1. Use project with latest bunq PHP API
2. Update composer dependencies, use `guzzlehttp/guzzle >=7.3`
3. Make bunq API calls

## What should happen:
1. Calls should succeed

## What happens:
1. An undefined function error comes up

## Traceback

> Error: Call to undefined function GuzzleHttp\Psr7\parse_query()
> #47 /vendor/bunq/sdk_php/src/Http/Pagination.php(126): bunq\Http\Pagination::updatePaginationBodyIdFieldFromResponseField
> #46 /vendor/bunq/sdk_php/src/Http/Pagination.php(88): bunq\Http\Pagination::parsePaginationBody
> #45 /vendor/bunq/sdk_php/src/Http/Pagination.php(59): bunq\Http\Pagination::restore
> #44 /vendor/bunq/sdk_php/src/Model/Core/BunqModel.php(312): bunq\Model\Core\BunqModel::fromJsonList
> #43 /vendor/bunq/sdk_php/src/Model/Generated/Endpoint/Event.php(146): bunq\Model\Generated\Endpoint\Event::listing
> #42 /app/Jobs/ProcessBunqAccountEvents.php(134): App\Jobs\ProcessBunqAccountEvents::handleInTransaction
> -- snip --

Sentry: https://sentry.io/share/issue/258e8c382d034eee9b64f170ea6d3ef2/

## SDK version and environment
- Tested on [1.14.18](https://github.com/bunq/sdk_php/releases/tag/1.14.18)
- [x] Sandbox
- [x] Production

## Extra info:
After quick inspection, it seems `guzzlehttp/guzzle >=7.3` started giving issues because of a changed API.

**Comment by RoodFruit** [comment]
Made a fork for people that don't want to wait ;)

https://github.com/RoodFruit/sdk_php

**Comment by timvisee** [comment]
> Made a fork for people that don't want to wait ;)
> 
> https://github.com/RoodFruit/sdk_php

This is already forked/patched with an open PR in https://github.com/bunq/sdk_php/pull/219

**Comment by RoodFruit** [comment]
@timvisee but it still isn't accepted ;)
