### ISSUE TITLE
Error in api context script

### ISSUE THREAD

**Issue by JvanHengel** [bunq/sdk_php#36]
# description
The scripts used to create an API context throw errors after inserting the API-key.
Error: 
```
"Fatal error: Cannot use isset() on the result of an expression (you can use "null !== expression" instead) in /my/project/path/vendor/bunq/sdk_php/src/Model/BunqModel.php on line 180"
```

# How to reproduce

- Run the command `"vendor/bin/bunq-install"` in the project root folder, the error will be thrown after entering the enviroment and API-key.
- Run the `"api_context_save_example.php"`.

**Comment by OGKevin** [comment]
@JvanHengel what version of PHP are you using ?

**Comment by JvanHengel** [comment]
PHP 5.6.31

**Comment by JvanHengel** [comment]
Fixed by updating to PHP 7.1.8

**Comment by OGKevin** [comment]
Ah that is nice to hear @JvanHengel 💪 , but reopening this issue as of `api_context_save_example.php` should work on php 5.6. Could not reproduce on `7.1`thought. Will setup a local env with `5.6` and try to reproduce.

**Comment by OGKevin** [comment]
Managed to reproduce this issue, it is indeed related to php5.6 looking for a fix.
