### ISSUE TITLE
"HTTP Response Code: 400 The request signature is invalid."

### ISSUE THREAD

**Issue by sanneterpstra** [bunq/sdk_php#87]
I'm trying to integrate the Bunq API in my Laravel project. The installation is flawless, however when I try to create a request I get an error "HTTP Response Code: 400. The request signature is invalid."

Has this something to do with the fact that I'm using [Laravel Valet](https://laravel.com/docs/5.5/valet) on my computer?

## Steps to reproduce:
1. Install SDK into laravel project

## What should happen:
1. Create apiContext and get users

## What happens:
1. apiContext gets created but the request fails with the following error:
`HTTP Response Code: 400. The request signature is invalid.`

**Comment by OGKevin** [comment]
@sanneterpstra What version of the SDK are you using, is it [0.12.4](https://github.com/bunq/sdk_php/releases/tag/0.12.4)?

If so i might also be related to: bunq/sdk_php#75

Could you see if this issue persists on [0.12.3](https://github.com/bunq/sdk_php/releases/tag/0.12.3)

**Comment by sanneterpstra** [comment]
Hi @OGKevin 

Yes I was using 0.12.4, it still persists in 0.12.3. Here is a little [screenshot](https://md105754.stackstorage.com/s/AkR2ZDjqji5ZFtt)

I'm using the newest version of Laravel Valet.

**Comment by OGKevin** [comment]
@sanneterpstra Hmmm I have a project running on `Laravel Valet 2.0.5` and a request to `user` works as intended. So I think we're hitting a weird corner case here :sweat_smile: 

Could you reproduce this error on the `sandbox` and send me the value of the `X-Bunq-Server-Response-Id` header. You can  var dump the raw response of the request to the `user` endpoint.

**Comment by sanneterpstra** [comment]
@OGKevin I solved the problem. An older version (5.4) of Laravel caused the error. Updating to Laravel 5.5 solved it. Thanks for your quick replies!
