### ISSUE TITLE
Add more example scripts

### ISSUE THREAD

**Issue by mbernson** [bunq/sdk_php#98]
This issue is meant to keep track of the example scripts included in the SDK.

- [x] ApiContext
  - [x] Save/restore
  - [ ] Ensure that session is active
- [x] Attachments
- [ ] Callbacks
- [ ] Cards
  - [x] Order card
- [ ] Card payments
  - [ ] MasterCard action
- [ ] Cash registers
- [ ] Chat
- [ ] Connects
- [x] Export statements
- [ ] Invoices
- [ ] Monetary accounts
- [ ] Payment
  - [ ] Draft Payment
  - [ ] Scheduled Payment
  - [x] Payment batch
  - [x] Tab Payment
- [x] Request for payment / Request inquiry
- [x] User

**Comment by OGKevin** [comment]
@mbernson Ive added one more check box to ApiContext. To show how to make sure that your session is indeed still active before you make a call.
